apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  labels:
    name: web 
    app: todoapp
spec:
  selector:
    name: nodejs
  type: NodePort
  ports:
   - name: http
     port: 5000
     targetPort: 5000
     nodePort: 30001
     protocol: TCP
