apiVersion: apps/v1
kind: Deployment
metadata:
  name: react
  labels:
    app: todoapp 
spec:
  replicas: 1
  selector:
    matchLabels:
      name: react
  template: 
    metadata:
      labels:
        name: react
        app: todoapp
    spec:
      containers: 
        - image: olivercw/react
          name: react
          ports: 
            - containerPort: 3000
          resources: {}
         