apiVersion: v1
kind: Service
metadata:
  name: react-service
  labels:
    name: web 
    app: todoapp
spec:
  selector:
    name: react
  type: NodePort
  ports:
   - port: 3000
     targetPort: 3000
     nodePort: 30002
     protocol: TCP
